### ISSUE TITLE
Poll config is impossible

### ISSUE THREAD

**Issue by skuran** [share-extras/site-poll-dashlet#1]
Alresco Community 4.2.e poll config is impossible even with admin or site manager. No config link appears. No exception in logs.

**Comment by wabson** [comment]
Thanks for reporting this. Any errors in the browser console? What browser are you using?

**Comment by skuran** [comment]
I'm using Firefox 36 with Firebug enabled. Dashlet can be added to dashboard without problem. Initially "No poll is configured" message appears. A window pops up when edit pencil is clicked. But there is no "Configure pool" link. Please see attched image. Javascript console shows no error.

Thank you for your reply.
![screen shot 2015-03-24 at 16 18 51](https://cloud.githubusercontent.com/assets/1818546/6803650/bd714352-d241-11e4-9619-faeef78deeaf.png)

**Comment by wabson** [comment]
The Configure link _is_ the pencil icon. But this refers to configuring the dashlet with a poll that already exists.

So you are correct if what you are saying is that the dialog does not allow you to create a new Poll. It was not designed to do this. In order to create a poll you need to create a new Datalist item of type _Poll_ inside the site.

Reference: https://github.com/share-extras/site-poll-dashlet#usage

**Comment by skuran** [comment]
Oh, my mistake, I should have read the usage, sorry. I thought Configure link was supposed to be somewhere in the dialog.

**Comment by wabson** [comment]
Thanks, no problem. Feel free to provide more feedback if the datalist does not work as expected.
